# Generated by Django 5.2.13 on 2026-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Cement', 'Cement'), ('Steel', 'Steel'), ('Timber', 'Timber'), ('Sand', 'Sand'), ('Roofing', 'Roofing'), ('Tiles', 'Tiles'), ('Paint', 'Paint'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Other', 'Other')], default='Other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='piece', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
                'ordering': ['category', 'name'],
            },
        ),
    ]
